### ISSUE TITLE
能否改成支持ES6语法,以及适配样式类型...

### ISSUE THREAD

**Issue by goldiwill** [ioing/IOING#1]
- 能否改成支持ES6语法，以及适配样式类型如，sass,scss,less,postcss...
- 是否支持嵌套路由
- 是子组件能否继承父组件的数据
///

**Comment by ioing** [comment]
第一个问题：项目可自由使用构建来支持ES6语法，这部分的方案暂时保留。sass,scss,less,postcss 这一部分引擎中自带了一个全新的解释器，它的定位是一个前端CSS扩展引擎，而不是一个预处理器，这是因为 引擎需要实时编译的描述语言。在语法上它和 sass,scss,less 等有些不同之处，但它更贴近标准CSS语言

第二个问题：支持嵌套路由

第三个问题：子组件默认继承父组件的数据
